### ISSUE TITLE
Kod jest kradziony!

### ISSUE THREAD

**Issue by czehu102** [MaybeUnknown/Example-Discord.js#2]
Komenda giveaway oraz komenda fortnite pochodzi z zamknietego bota OneBot. Prosze o wyjasnienie tej sprawy. Nie ma szans że ten kod jest od kogoś innego - jest kradziony. Poza tym radziłbym dodać licencję, jeżeli właściwy autor czołgista_mateusz#6075 o ID 566521151459819530 nie chce, żeby kradli jego ukradziony kod.

Pozdrawiam.
VeX
OneBot Global Developer.

**Comment by rkubapl** [comment]
Są inne boty z komenda giveaway i są też inne boty z komenda fortnite.
Więc nie pisz że kod jest kradziony jak ileś botów ma taką funkcję.

Pozdrawiam
